[PHP]
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
error_log = /var/log/php_errors.log

memory_limit = 256M
max_execution_time = 300
max_input_time = 300

upload_max_filesize = 20M
post_max_size = 20M
max_file_uploads = 20

[Date]
date.timezone = Europe/Prague

[opcache]
opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 60

[xdebug]
xdebug.mode = debug,coverage
xdebug.start_with_request = no
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
